name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: production
      PORT: 3001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (optional)
        run: npm test
        continue-on-error: true

      - name: Build (if needed)
        run: npm run build --if-present

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}